#!/bin/bash
    
perf record -F 49 -a -g --sleep 10; perf script --header out.stacks

# Check if the first argument is 1
if [ "$1" -eq 1 ]; then
    # Clone the FlameGraph repository if it doesn't already exist
    if [ ! -d "FlameGraph" ]; then
        git clone https://github.com/brendangregg/FlameGraph
    else
        echo "FlameGraph directory already exists, skipping clone..."
    fi
    cd FlameGraph
fi

./stackcollapse-perf.pl < ../out.stacks | ./flamegraph.pl --hash > out.svg
